#!/usr/bin/env python3
"""IAF MA150 Forward-Survival Bridge Script.

Statistically compares two entry-gate tiers ("current" 7-of-7 vs the INCREMENTAL
signals "structural_2of3" adds beyond current -- see the conf_s23-and-not-conf_curr
filter below, fixes a double-count CodeRabbit caught 2026-08-31) on
the probability that the underlying stock stays above its signal-day MA150
support level over a 30-trading-day forward window across walk-forward backtest
windows generated by the investing-algorithm-framework (v8.10.0).

Isolated evaluation script -- does not modify aria-trading codebase.
"""
from __future__ import annotations

import argparse
import csv
from datetime import datetime, timezone
import os
from pathlib import Path
import sys
import time
from typing import Any, Dict, List, Tuple

import numpy as np
import pandas as pd
import yfinance as yf
from investing_algorithm_framework import (
    BacktestDateRange,
    generate_rolling_backtest_windows,
)

# Import signal_core from aria-trading repo (script lives at
# <repo>/scripts/research/, so repo root is two levels up)
REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

import signal_core  # noqa: E402
from signal_core import (  # noqa: E402
    CONFIRM_KEYS,
    DEFAULT_GATE_KEYS,
    MA50_BAND,
    MA150_BAND,
    MIN_BARS,
    RSI_LENGTH,
    RSI_THRESHOLD,
    STRUCTURAL_KEYS,
    VOLUME_MA_LENGTH,
    candle_pattern,
    rsi_series,
)


def ema_series(values: List[float], length: int) -> List[float | None]:
    """Incremental Exponential Moving Average, one value per bar (None where undefined)."""
    out: List[float | None] = [None] * len(values)
    if len(values) < length:
        return out
    e = sum(values[:length]) / length
    out[length - 1] = e
    k = 2.0 / (length + 1)
    for i in range(length, len(values)):
        e = values[i] * k + e * (1 - k)
        out[i] = e
    return out


def sma_series(values: List[float], length: int) -> List[float | None]:
    """Rolling Simple Moving Average, one value per bar (None where undefined)."""
    out: List[float | None] = [None] * len(values)
    if len(values) < length:
        return out
    for i in range(length - 1, len(values)):
        out[i] = sum(values[i - length + 1 : i + 1]) / length
    return out


def evaluate_entry(
    close: float,
    volume: float,
    bar: Dict[str, Any],
    prev_bar: Dict[str, Any] | None,
    rsi_now: float | None,
    rsi_prev: float | None,
    ma50: float | None,
    ma150: float | None,
    vol_ma20: float | None,
) -> Tuple[bool, bool]:
    """Evaluate entry gates (current 7-of-7 and structural 2-of-3) for a single bar.

    Reuses signal_core's exact key sets, bands, thresholds, and candle pattern logic
    with precomputed O(1) indicators instead of O(n) prefix rescans.
    Returns (conf_curr, conf_s23).
    """
    below_ma50_pct = (ma50 - close) / ma50 if ma50 else None
    above_ma150_pct = (close - ma150) / ma150 if ma150 else None

    checks = {
        "above_ma150": ma150 is not None and close > ma150,
        "rsi_below_50": rsi_now is not None and rsi_now < RSI_THRESHOLD,
        "rsi_rising": (rsi_now is not None and rsi_prev is not None and rsi_now > rsi_prev),
        "near_ma50_pullback": (below_ma50_pct is not None and MA50_BAND[0] <= below_ma50_pct <= MA50_BAND[1]),
        "near_ma150_support": (above_ma150_pct is not None and MA150_BAND[0] <= above_ma150_pct <= MA150_BAND[1]),
        "volume_above_avg": vol_ma20 is not None and volume > vol_ma20,
    }
    pattern = candle_pattern(
        bar["open"], bar["high"], bar["low"], bar["close"],
        prev_bar["open"] if prev_bar is not None else None,
        prev_bar["close"] if prev_bar is not None else None,
    )
    checks["bullish_candle"] = pattern != "none"
    checks["candle_pattern"] = pattern

    conf_curr = all(checks[k] for k in DEFAULT_GATE_KEYS)
    struct_passed = sum(1 for k in STRUCTURAL_KEYS if checks.get(k, False)) >= 4
    conf_passed = sum(1 for k in CONFIRM_KEYS if checks.get(k, False)) >= 2
    conf_s23 = struct_passed and conf_passed

    return conf_curr, conf_s23


def load_universe_tickers(universe_path: Path) -> List[str]:
    """Load tickers from data/universe.csv."""
    tickers = []
    with open(universe_path, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            t = row.get("ticker", "").strip()
            if t:
                tickers.append(t)
    return tickers


def fetch_historical_data(
    tickers: List[str], start_date: str, end_date: str
) -> pd.DataFrame:
    """Fetch batched daily OHLCV via yfinance using the prescreen.py pattern."""
    print(f"Fetching batched OHLCV for {len(tickers)} tickers ({start_date} to {end_date})...")
    t0 = time.time()
    df = yf.download(
        tickers,
        start=start_date,
        end=end_date,
        interval="1d",
        auto_adjust=False,
        group_by="ticker",
        threads=True,
        progress=False,
    )
    t1 = time.time()
    print(f"Data fetch completed in {t1 - t0:.2f}s. MultiIndex shape: {df.shape}")
    return df


def extract_ticker_data(
    df: pd.DataFrame, ticker: str, total_tickers: int
) -> Tuple[
    List[Dict[str, Any]],
    List[float],
    List[float],
    List[float | None],
    List[float | None],
    List[float | None],
    List[float | None],
] | None:
    """Extract and validate clean bar history for a single ticker."""
    if isinstance(df.columns, pd.MultiIndex):
        if ticker not in df.columns.levels[0]:
            return None
        try:
            tdf = df[ticker]
            if not isinstance(tdf, pd.DataFrame) or tdf.empty:
                return None
        except (KeyError, TypeError):
            return None
    else:
        if total_tickers == 1:
            tdf = df
        else:
            return None

    required_cols = ["Open", "High", "Low", "Close", "Volume"]
    if not all(c in tdf.columns for c in required_cols):
        return None

    tdf = tdf.dropna(subset=required_cols)
    if len(tdf) < MIN_BARS:
        return None

    tdf = tdf.sort_index()

    bars = []
    for idx, row in tdf.iterrows():
        bar_date = idx.strftime("%Y-%m-%d") if hasattr(idx, "strftime") else str(idx)[:10]
        bars.append({
            "date": bar_date,
            "timestamp": pd.Timestamp(idx).tz_localize(None),
            "open": float(row["Open"]),
            "high": float(row["High"]),
            "low": float(row["Low"]),
            "close": float(row["Close"]),
            "volume": float(row["Volume"]),
        })

    if len(bars) < MIN_BARS:
        return None

    closes = [b["close"] for b in bars]
    volumes = [b["volume"] for b in bars]
    rsis = rsi_series(closes, RSI_LENGTH)
    ema150s = ema_series(closes, 150)
    sma50s = sma_series(closes, 50)
    vol_ma20s = sma_series(volumes, VOLUME_MA_LENGTH)

    return bars, closes, volumes, rsis, ema150s, sma50s, vol_ma20s


def run_permutation_test(
    outcomes_a: List[int],
    outcomes_b: List[int],
    n_permutations: int = 10000,
    seed: int = 42,
) -> Tuple[float | None, float | None, float, float, float]:
    """Two-proportion permutation test using numpy Hypergeometric sampling.

    Under H0, successes follow Hypergeometric(N, K, n_a).
    Returns (p_value_two_sided, p_value_one_sided, diff_obs, rate_a, rate_b).
    p_value_two_sided/p_value_one_sided are None if either arm has zero
    signals -- the comparison is undefined, not "no difference found".

    KNOWN LIMITATION (CodeRabbit finding, 2026-09-15, not yet fixed):
    treats every (ticker, window) signal as an independent Bernoulli trial.
    Multiple signals from the SAME ticker with overlapping 30-day forward
    windows are correlated (they can share forward-window trading days and
    the same underlying trend), violating i.i.d. -- the reported p=0.87 (see
    docs/research-methodology.md) likely understates the true uncertainty.
    Deferred rather than guessed at: a correct fix needs a real design
    decision on cluster granularity (per-ticker? per-ticker-per-overlapping-
    window-group, given windows can overlap in complex ways within one
    ticker?) before rewriting this as a block/cluster permutation instead of
    a flat hypergeometric shuffle -- not something to redesign blind.
    Directionally, clustering corrections generally make significance tests
    MORE conservative (wider effective uncertainty from fewer truly-
    independent observations), so this is far more likely to reinforce the
    current "no significant difference" conclusion than overturn it -- but
    that is a plausibility argument, not a substitute for the actual fix.
    """
    n_a = len(outcomes_a)
    n_b = len(outcomes_b)
    if n_a == 0 or n_b == 0:
        # Undefined, not "no difference": there's nothing to compare. Return
        # None p-values so the caller reports "comparison unavailable"
        # rather than a misleading p=1.0 "not significant" verdict on zero
        # signals (CodeRabbit finding, 2026-08-31).
        rate_a = float(np.mean(outcomes_a)) if n_a else 0.0
        rate_b = float(np.mean(outcomes_b)) if n_b else 0.0
        return None, None, rate_a - rate_b, rate_a, rate_b

    rate_a = float(np.mean(outcomes_a))
    rate_b = float(np.mean(outcomes_b))
    diff_obs = rate_a - rate_b

    k_a = int(np.sum(outcomes_a))
    k_b = int(np.sum(outcomes_b))
    total_k = k_a + k_b
    total_n = n_a + n_b

    rng = np.random.default_rng(seed)
    # Simulate distribution of k_a under null permutation
    sim_k_a = rng.hypergeometric(
        ngood=total_k, nbad=total_n - total_k, nsample=n_a, size=n_permutations
    )
    sim_k_b = total_k - sim_k_a
    sim_diffs = (sim_k_a / n_a) - (sim_k_b / n_b)

    # Add-one (Davison & Hinkley) correction: a finite Monte Carlo estimate
    # can never truthfully claim p=0.0 -- if the observed difference is more
    # extreme than every single simulated draw, the honest bound is 1/(N+1),
    # not 0. CodeRabbit finding, 2026-08-31.
    extreme_two = int(np.sum(np.abs(sim_diffs) >= np.abs(diff_obs)))
    extreme_one = int(np.sum(sim_diffs >= diff_obs)) if diff_obs >= 0 else int(np.sum(sim_diffs <= diff_obs))
    p_two = (extreme_two + 1) / (n_permutations + 1)
    p_one = (extreme_one + 1) / (n_permutations + 1)

    return p_two, p_one, diff_obs, rate_a, rate_b


def main():
    parser = argparse.ArgumentParser(
        description="IAF MA150 Forward-Survival Walk-Forward Bridge"
    )
    parser.add_argument(
        "--universe",
        default=str(REPO_ROOT / "data" / "universe.csv"),
        help="Path to universe.csv",
    )
    parser.add_argument(
        "--start-date",
        default="2022-01-01",
        help="Start date for historical data download (default: 2022-01-01 to give 1yr warm-up before 2023)",
    )
    parser.add_argument(
        "--walk-start-date",
        default="2023-01-01",
        help="Start date for IAF rolling backtest windows (default: 2023-01-01)",
    )
    parser.add_argument(
        "--train-days",
        type=int,
        default=365,
        help="IAF rolling window train_days (default: 365)",
    )
    parser.add_argument(
        "--test-days",
        type=int,
        default=90,
        help="IAF rolling window test_days (default: 90)",
    )
    parser.add_argument(
        "--step-days",
        type=int,
        default=90,
        help="IAF rolling window step_days (default: 90)",
    )
    def positive_int(value: str) -> int:
        ivalue = int(value)
        if ivalue <= 0:
            raise argparse.ArgumentTypeError(f"must be a positive integer, got {value}")
        return ivalue

    parser.add_argument(
        "--forward-days",
        type=positive_int,
        default=30,
        help="Forward trading days for MA150 survival evaluation (default: 30, must be > 0)",
    )
    parser.add_argument(
        "--permutations",
        type=positive_int,
        default=10000,
        help="Number of permutations for significance test (default: 10000, must be > 0)",
    )
    args = parser.parse_args()

    total_start_time = time.time()

    universe_path = Path(args.universe)
    if not universe_path.exists():
        print(f"Error: universe file not found at {universe_path}", file=sys.stderr)
        sys.exit(1)

    tickers = load_universe_tickers(universe_path)
    total_tickers = len(tickers)
    print(f"Loaded {total_tickers} tickers from {universe_path}")

    now_utc = datetime.now(timezone.utc)
    today_str = now_utc.strftime("%Y-%m-%d")

    # 1. Batched Data Download
    fetch_t0 = time.time()
    df_raw = fetch_historical_data(tickers, args.start_date, today_str)
    fetch_time = time.time() - fetch_t0

    # 2. Extract & Precompute Indicators per Ticker
    print("Precomputing indicators (MA50/SMA, MA150/EMA, Wilder RSI, candle patterns)...")
    prep_t0 = time.time()
    ticker_data_map: Dict[
        str,
        Tuple[
            List[Dict[str, Any]],
            List[float],
            List[float],
            List[float | None],
            List[float | None],
            List[float | None],
            List[float | None],
        ],
    ] = {}
    failed_tickers: List[str] = []

    for t in tickers:
        res = extract_ticker_data(df_raw, t, total_tickers)
        if res is None:
            failed_tickers.append(t)
        else:
            ticker_data_map[t] = res

    prep_time = time.time() - prep_t0
    print(
        f"Preprocessed {len(ticker_data_map)} valid tickers in {prep_time:.2f}s "
        f"({len(failed_tickers)} failed/insufficient data: {', '.join(failed_tickers[:10])}{'...' if len(failed_tickers) > 10 else ''})"
    )

    # 3. Generate IAF Walk-Forward Windows
    walk_start = datetime.strptime(args.walk_start_date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    walk_end = now_utc

    iaf_windows = generate_rolling_backtest_windows(
        start_date=walk_start,
        end_date=walk_end,
        train_days=args.train_days,
        test_days=args.test_days,
        step_days=args.step_days,
        gap_days=0,
    )
    print(
        f"Generated {len(iaf_windows)} IAF walk-forward windows "
        f"(train_days={args.train_days}, test_days={args.test_days}, step_days={args.step_days})"
    )

    # 4. Evaluate Entry Gates & 30-Day MA150 Forward Survival
    eval_t0 = time.time()
    forward_days = args.forward_days

    # Pre-parse window date boundaries and initialize per-window accumulators
    window_entries: List[Dict[str, Any]] = []
    for w_idx, win in enumerate(iaf_windows):
        test_range: BacktestDateRange = win["test_range"]
        w_start_ts = pd.Timestamp(test_range.start_date).tz_localize(None)
        w_end_ts = pd.Timestamp(test_range.end_date).tz_localize(None)
        w_name = test_range.name or f"window_{w_idx+1}"
        window_entries.append({
            "window_idx": w_idx + 1,
            "name": w_name,
            "start": w_start_ts.strftime("%Y-%m-%d"),
            "end": w_end_ts.strftime("%Y-%m-%d"),
            "start_ts": w_start_ts,
            "end_ts": w_end_ts,
            "current_signals": 0,
            "current_survived": 0,
            "current_outcomes": [],
            "s23_signals": 0,
            "s23_survived": 0,
            "s23_outcomes": [],
        })

    overall_start = min(w["start_ts"] for w in window_entries) if window_entries else None
    overall_end = max(w["end_ts"] for w in window_entries) if window_entries else None

    # Single pass over each (ticker, bar) across all windows
    for ticker, (bars, closes, volumes, rsis, ema150s, sma50s, vol_ma20s) in ticker_data_map.items():
        n_bars = len(bars)
        for i in range(MIN_BARS - 1, n_bars):
            bar_ts = bars[i]["timestamp"]
            if overall_start is None or bar_ts < overall_start or bar_ts >= overall_end:
                continue
            if i + forward_days >= n_bars:
                continue

            matching_windows = [w for w in window_entries if w["start_ts"] <= bar_ts < w["end_ts"]]
            if not matching_windows:
                continue

            conf_curr, conf_s23 = evaluate_entry(
                close=closes[i],
                volume=volumes[i],
                bar=bars[i],
                prev_bar=bars[i - 1],
                rsi_now=rsis[i],
                rsi_prev=rsis[i - 1] if i >= 1 else None,
                ma50=sma50s[i],
                ma150=ema150s[i],
                vol_ma20=vol_ma20s[i],
            )

            if not conf_curr and not conf_s23:
                continue

            # Signal day MA150 (held fixed over the forward 30-day window)
            signal_ema150 = ema150s[i]
            if signal_ema150 is None:
                continue

            # 30 trading days forward closes
            forward_closes = closes[i + 1 : i + 1 + forward_days]
            # Survived if close NEVER fell below signal_ema150
            min_fwd_close = min(forward_closes)
            survived = int(min_fwd_close >= signal_ema150)

            for w in matching_windows:
                if conf_curr:
                    w["current_signals"] += 1
                    w["current_survived"] += survived
                    w["current_outcomes"].append(survived)

                # current and s23 are NOT nested (CodeRabbit finding,
                # 2026-09-15): current's DEFAULT_GATE_KEYS never requires
                # near_ma50_pullback, but s23's min_structural=4 requires ALL
                # four STRUCTURAL_KEYS including it -- so current=True does
                # NOT imply s23=True. They're two independent, overlapping
                # tiers, not one a strict superset of the other. The sets DO
                # still intersect (whenever near_ma50_pullback also holds on
                # a bar that already passes current, since current's
                # rsi_rising+bullish_candle alone already clear s23's
                # min_confirm=2). Counting an overlap signal into BOTH pools
                # would violate the two-proportion test's independence
                # assumption, so it's counted only once, in the `conf_curr`
                # pool above -- this block only takes s23-only signals,
                # keeping the two pools disjoint. This is a "signals the
                # loosened s23 tier accepts that the current gate doesn't"
                # comparison, not an "incremental signals added on top of
                # current" one.
                if conf_s23 and not conf_curr:
                    w["s23_signals"] += 1
                    w["s23_survived"] += survived
                    w["s23_outcomes"].append(survived)

    # Reconstruct window_results and pooled outcomes preserving window order
    window_results: List[Dict[str, Any]] = []
    pooled_current_outcomes: List[int] = []
    pooled_s23_outcomes: List[int] = []

    for w in window_entries:
        curr_signals = w["current_signals"]
        curr_survived = w["current_survived"]
        s23_signals = w["s23_signals"]
        s23_survived = w["s23_survived"]

        curr_rate = (curr_survived / curr_signals * 100.0) if curr_signals > 0 else 0.0
        s23_rate = (s23_survived / s23_signals * 100.0) if s23_signals > 0 else 0.0

        window_results.append({
            "window_idx": w["window_idx"],
            "name": w["name"],
            "start": w["start"],
            "end": w["end"],
            "current_signals": curr_signals,
            "current_survived": curr_survived,
            "current_rate": curr_rate,
            "s23_signals": s23_signals,
            "s23_survived": s23_survived,
            "s23_rate": s23_rate,
            "rate_diff_pp": curr_rate - s23_rate,
        })
        pooled_current_outcomes.extend(w["current_outcomes"])
        pooled_s23_outcomes.extend(w["s23_outcomes"])

    eval_time = time.time() - eval_t0

    # 5. Significance Testing
    perm_t0 = time.time()
    p_two, p_one, diff_obs, rate_curr, rate_s23 = run_permutation_test(
        pooled_current_outcomes, pooled_s23_outcomes, n_permutations=args.permutations
    )
    perm_time = time.time() - perm_t0

    total_time = time.time() - total_start_time

    # 6. Print Report
    print("\n" + "=" * 90)
    print("IAF MA150 FORWARD-SURVIVAL WALK-FORWARD EVALUATION REPORT")
    print("=" * 90)
    print(f"Dataset: {len(ticker_data_map)} tickers | Date range: {args.start_date} to {today_str}")
    print(f"Forward Horizon: {forward_days} trading days | MA150 Survival: close >= signal_ema150 for all {forward_days} days")
    print("-" * 90)
    print(
        f"{'Window':<8} {'Test Period':<24} | "
        f"{'Current (7-of-7)':<22} | "
        f"{'Structural 2-of-3 (incr.)':<22} | "
        f"{'Delta (pp)':<10}"
    )
    print(
        f"{'':<8} {'':<24} | "
        f"{'Signals':<8} {'Surv':<6} {'Rate %':<7} | "
        f"{'Signals':<8} {'Surv':<6} {'Rate %':<7} | "
        f"{'':<10}"
    )
    print("-" * 90)

    for wr in window_results:
        w_period = f"{wr['start']} .. {wr['end']}"
        curr_str = f"{wr['current_signals']:<8} {wr['current_survived']:<6} {wr['current_rate']:>6.1f}%"
        s23_str = f"{wr['s23_signals']:<8} {wr['s23_survived']:<6} {wr['s23_rate']:>6.1f}%"
        delta_str = f"{wr['rate_diff_pp']:>+7.1f}%" if (wr['current_signals'] > 0 and wr['s23_signals'] > 0) else "   N/A"
        
        # Check for sparse signal counts
        note = ""
        if wr['current_signals'] < 10 or wr['s23_signals'] < 10:
            note = " [sparse]"

        print(f"W{wr['window_idx']:<2} ({wr['name'][:6]}) {w_period:<24} | {curr_str} | {s23_str} | {delta_str}{note}")

    print("-" * 90)

    total_curr_sig = len(pooled_current_outcomes)
    total_curr_surv = sum(pooled_current_outcomes)
    total_s23_sig = len(pooled_s23_outcomes)
    total_s23_surv = sum(pooled_s23_outcomes)

    pooled_curr_pct = (total_curr_surv / total_curr_sig * 100.0) if total_curr_sig > 0 else 0.0
    pooled_s23_pct = (total_s23_surv / total_s23_sig * 100.0) if total_s23_sig > 0 else 0.0
    pooled_delta = pooled_curr_pct - pooled_s23_pct

    print(
        f"{'POOLED':<33} | "
        f"{total_curr_sig:<8} {total_curr_surv:<6} {pooled_curr_pct:>6.1f}% | "
        f"{total_s23_sig:<8} {total_s23_surv:<6} {pooled_s23_pct:>6.1f}% | "
        f"{pooled_delta:>+7.1f}%"
    )
    print("=" * 90)

    # 7. Statistical Test Results & Verdict
    alpha = 0.05
    print(f"\nSTATISTICAL SIGNIFICANCE TEST (Two-Proportion Permutation Test, N={args.permutations:,}):")
    print(f"  - Null Hypothesis (H0): Survival rate(Current) == Survival rate(Structural 2-of-3, incremental-only)")
    print(f"  - Current (7-of-7):       {total_curr_surv}/{total_curr_sig} ({pooled_curr_pct:.2f}%)")
    print(f"  - Structural 2-of-3 (incr.): {total_s23_surv}/{total_s23_sig} ({pooled_s23_pct:.2f}%)")
    print(f"  - Observed Difference:    {pooled_delta:+.2f} percentage points")

    if p_two is None:
        verdict = (
            "COMPARISON UNAVAILABLE -- one or both tiers produced zero signals "
            "in this run (see counts above), so a significance test isn't "
            "meaningful. This is not the same as 'not significant' -- widen "
            "the date range/universe or check the gate parameters."
        )
        print(f"  - Permutation p-value:    N/A (undefined)")
    else:
        print(f"  - Permutation p-value:    {p_two:.4f} (two-sided), {p_one:.4f} (one-sided)")
        is_sig = p_two < alpha
        if is_sig:
            verdict = (
                f"STATISTICALLY SIGNIFICANT at alpha={alpha} (p={p_two:.4f} < {alpha}). "
                f"The difference of {abs(pooled_delta):.2f} percentage points between tiers is unlikely due to chance."
            )
        else:
            verdict = (
                f"NOT STATISTICALLY SIGNIFICANT at alpha={alpha} (p={p_two:.4f} >= {alpha}). "
                f"The survival rate difference of {abs(pooled_delta):.2f} percentage points is consistent with random chance."
            )

    print(f"\nVERDICT: {verdict}")

    print("\nPERFORMANCE & EXECUTION TIMING:")
    print(f"  - Data fetch (yfinance):   {fetch_time:.2f}s")
    print(f"  - Indicator preprocessing: {prep_time:.2f}s")
    print(f"  - Walk-forward evaluation: {eval_time:.2f}s")
    print(f"  - Permutation test:        {perm_time:.2f}s")
    print(f"  - Total run time:          {total_time:.2f}s ({total_time/60:.2f} min)")
    print("=" * 90)


if __name__ == "__main__":
    main()
